FORMAT: 1A
HOST: http://products.apiblueprint.org/

# test-api

Products is a simple api to test the amazing features of apiblueprint format!

## Products Collection [/products/{id}]

### List All Products [GET]

Retrieve all the products

+ Parameters
    + id (number, optional) ... Filter by the given product id.

+ Response 200 (application/json)
    + Attributes
        - products (Product)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 404 (application/json)

        {
          "error": "Not found",
          "error_description": "The requested resource does not found."
        }

### Create a New Product [POST]

You can create your own products by posting a new resource with all its details.

+ Request (application/json)

        {
            "name": "Product 5",
            "type": "EVENT"
        }

+ Response 201 (application/json)

    + Headers

            Location: /products/5

    + Body

            {
                [
                    {
                        "id": 5,
                        "name": "Product 5",
                        "type": "ACTIVITY"
                    }
                ]
            }

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 404 (application/json)

        {
          "error": "Not found",
          "error_description": "The requested resource does not found."
        }

### Update a Product [PUT]

You can modify a given product by putting a new resource details.

+ Request (application/json)

        {
            "id": 3
            "name": "Product 3",
            "type": "ACTIVITY"
        }

+ Response 200 (application/json)

    + Headers

            Location: /products/3

    + Body

            {
                [
                    {
                        "id": 3,
                        "name": "Product 3",
                        "type": "ACTIVITY"
                    }
                ]
            }

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 404 (application/json)

        {
          "error": "Not found",
          "error_description": "The requested resource does not found."
        }

+ Response 201 (application/json)

    + Headers

            Location: /products/3

    + Body

            {
                [
                    {
                        "id": 3,
                        "name": "Product 3",
                        "type": "ACTIVITY"
                    }
                ]
            }
            
### Delete a Product [DELETE]

You can delete a given product identified by its id.

+ Response 200 (application/json)

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 404 (application/json)

        {
          "error": "Not found",
          "error_description": "The requested resource does not found."
        }
        
# Data Structures

## Product (object)

- id: `1` (number)
- name: `Product 1` (string)
- type: `EVENT` (string)